services:
  transactions:
    image: ghcr.io/leocosta-dev/transferapigolang-transactions:latest
    env_file:
      - .env
    environment:
      TRANSACTIONS_HTTP_ADDR: ":8089"
    ports:
      - "127.0.0.1:8089:8089"
    restart: unless-stopped

  account:
    image: ghcr.io/leocosta-dev/transferapigolang-account:latest
    env_file:
      - .env
    environment:
      ACCOUNT_HTTP_ADDR: ":8088"
      TRANSACTIONS_SERVICE_URL: "http://transactions:8089"
    depends_on:
      - transactions
    ports:
      - "127.0.0.1:8088:8088"
    restart: unless-stopped